name: 'Android Build'
description: 'Build Android projects'
author: 'Veaceslav Gaidarji <veaceslav.gaidarji@gmail.com>'
branding:
  icon: 'box'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
